"""Initial migration

Revision ID: 9c8491f841e7
Revises: 
Create Date: 2024-04-16 01:06:16.164753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8491f841e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uID'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('channel',
    sa.Column('cID', sa.Integer(), nullable=False),
    sa.Column('creatorID', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creatorID'], ['user.uID'], ),
    sa.PrimaryKeyConstraint('cID')
    )
    op.create_table('message',
    sa.Column('mID', sa.Integer(), nullable=False),
    sa.Column('senderID', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['senderID'], ['user.uID'], ),
    sa.PrimaryKeyConstraint('mID')
    )
    op.create_table('playlist',
    sa.Column('pID', sa.Integer(), nullable=False),
    sa.Column('uID', sa.Integer(), nullable=False),
    sa.Column('playlist_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uID'], ['user.uID'], ),
    sa.PrimaryKeyConstraint('pID')
    )
    op.create_table('session',
    sa.Column('sID', sa.Integer(), nullable=False),
    sa.Column('uID', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uID'], ['user.uID'], ),
    sa.PrimaryKeyConstraint('sID')
    )
    op.create_table('study_group',
    sa.Column('sgID', sa.Integer(), nullable=False),
    sa.Column('creatorID', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creatorID'], ['user.uID'], ),
    sa.PrimaryKeyConstraint('sgID')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.uID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ChannelMessage',
    sa.Column('cID', sa.Integer(), nullable=False),
    sa.Column('mID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cID'], ['channel.cID'], ),
    sa.ForeignKeyConstraint(['mID'], ['message.mID'], ),
    sa.PrimaryKeyConstraint('cID', 'mID')
    )
    op.create_table('StudyGroupChannel',
    sa.Column('sgID', sa.Integer(), nullable=False),
    sa.Column('cID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cID'], ['channel.cID'], ),
    sa.ForeignKeyConstraint(['sgID'], ['study_group.sgID'], ),
    sa.PrimaryKeyConstraint('sgID', 'cID')
    )
    op.create_table('StudyGroupMember',
    sa.Column('uID', sa.Integer(), nullable=False),
    sa.Column('sgID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sgID'], ['study_group.sgID'], ),
    sa.ForeignKeyConstraint(['uID'], ['user.uID'], ),
    sa.PrimaryKeyConstraint('uID', 'sgID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('StudyGroupMember')
    op.drop_table('StudyGroupChannel')
    op.drop_table('ChannelMessage')
    op.drop_table('todo')
    op.drop_table('study_group')
    op.drop_table('session')
    op.drop_table('playlist')
    op.drop_table('message')
    op.drop_table('channel')
    op.drop_table('user')
    # ### end Alembic commands ###
